@prefix deps:  <http://ontologi.es/doap-deps#> .

<http://purl.org/NET/cpan-uri/dist/Class-Method-ModifiersX-Augment/project>
	deps:runtime-recommendation      [ deps:on "Moo"^^deps:CpanId ];
	deps:runtime-recommendation      [ deps:on "MRO::Compat"^^deps:CpanId ];
	deps:runtime-requirement         [ deps:on "Class::Method::Modifiers"^^deps:CpanId ];
	deps:test-requirement            [ deps:on "Test::More 0.61"^^deps:CpanId ].

